name: CI

on: 
  push:
   branches:
     - master 

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo in container
      uses: actions/checkout@v1
      
    - name: save envs
      uses: maddox/actions/ssh@master
      env:
        PRIVATE_KEY: ${{ secrets.KEY }}
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
        REPO: "https://github.com/mandarin801/actions-pg.git"
      with:
        args: |
          [ -d ./actions-pg ] || git clone https://github.com/mandarin801/actions-pg.git
          cd actions-pg
          git fetch https://github.com/mandarin801/actions-pg.git
          chmod +x test.sh
          ./test.sh

#     - name: execute ssh task
#       run: |
#         echo ${{ secrets.KEY }} >> id_rsa
#         ssh -i id_rsa ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'ls -lah'

    # steps:
    # - name: executing remote ssh commands using password
    #   uses: JimCronqvist/action-ssh@0.1.1
    #   env:
    #     NAME: "GITHUB"
    #   with:
    #     hosts: ${{ secrets.HOST }}
    #     username: ${{ secrets.USERNAME }}
    #     privateKey: ${{ secrets.KEY }}
    #     command: |
    #       ls -lah
    #       echo "I am $NAME"
          
