name: CI

on: 
  push:
   branches:
     - master 

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: JimCronqvist/action-ssh@master
      with:
        hosts: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        privateKey: ${{ secrets.KEY }}
        command: whoami
